### ISSUE TITLE
dead link about `How to restart a docker container`

### ISSUE THREAD

**Issue by KenYurino** [scalar-labs/scalar-terraform#234]
Can't find the link to `How to restart a docker container` and can't refer to the documentation.

https://github.com/scalar-labs/scalar-terraform/blob/master/docs/ScalarDLClusterDown.md#related-guide

Also, I couldn't find documentation for the ENVOY startup procedure, is there?

**Comment by feeblefakie** [comment]
It's written here. 
https://github.com/scalar-labs/scalar-terraform/blob/master/docs/ScalarDLClusterDown.md#related-guide

For more detail about Docker and Docker compose, please refer the official guides of them.
