### ISSUE TITLE
I need to know the version of Terraform to run this tool.

### ISSUE THREAD

**Issue by scalar-kato** [scalar-labs/scalar-terraform#318]
The README for this tool states that the version of Terraform is v0.14.x.
https://github.com/scalar-labs/scalar-terraform#requirements

I think this tool is using [terraform-aws-vpc](https://github.com/scalar-labs/terraform-aws-vpc).
https://github.com/scalar-labs/scalar-terraform/blob/master/modules/aws/network/main.tf#L7

But the README for terraform-aws-vpc says it only supports up to v0.12.x of terraform.
https://github.com/scalar-labs/terraform-aws-vpc#terraform-versions

So please let me know which version of Terraform this tool will work with.

**Comment by tei-k** [comment]
>So please let me know which version of Terraform this tool will work with.

Just support `0.14.x`, The latest version of `0.14` is recommended.

>But the README for terraform-aws-vpc says it only supports up to v0.12.x of terraform.

It's a forked repository, so I haven't updated the README, but it supports `0.14`.

See examples for version details.

e.g.) aws network module
https://github.com/scalar-labs/scalar-terraform-examples/blob/main/aws/network/.terraform.lock.hcl
https://github.com/scalar-labs/scalar-terraform-examples/blob/main/aws/network/versions.tf
